name: Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .docker/.Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/woocommerce-podman:${{ github.ref_name }}
          ghcr.io/${{ github.repository_owner }}/woocommerce-podman:${{ github.ref_name }}
          ${{ secrets.DOCKERHUB_USERNAME }}/woocommerce-podman:latest
          ghcr.io/${{ github.repository_owner }}/woocommerce-podman:latest

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: |
          Docker images are available (latest tag is always the same as the tag of the release)
          Release tag: ${{ github.ref_name }}
          
          DockerHub:
          ```
          podman pull docker.io/${{ secrets.DOCKERHUB_USERNAME }}/woocommerce-podman:${{ github.ref_name }}
          ```
          
          ```
          podman pull docker.io/${{ secrets.DOCKERHUB_USERNAME }}/woocommerce-podman:latest
          ```

          GitHub Container Registry:
          ```
          podman pull ghcr.io/${{ github.repository_owner }}/woocommerce-podman:${{ github.ref_name }}
          ```
          
          ```
          podman pull ghcr.io/${{ github.repository_owner }}/woocommerce-podman:latest
          ```